"""initial schema

Revision ID: 7777bbd3ef3a
Revises: 
Create Date: 2026-06-12 16:40:10.201750
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7777bbd3ef3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('entry_z', sa.Float(), nullable=False),
    sa.Column('exit_z', sa.Float(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('avg_reversion_bps', sa.Float(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=False),
    sa.Column('max_drawdown_bps', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonds',
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('coupon', sa.Float(), nullable=False),
    sa.Column('maturity', sa.Date(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=False),
    sa.Column('coupon_freq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cusip')
    )
    op.create_index(op.f('ix_bonds_issuer'), 'bonds', ['issuer'], unique=False)
    op.create_index(op.f('ix_bonds_rating'), 'bonds', ['rating'], unique=False)
    op.create_index(op.f('ix_bonds_sector'), 'bonds', ['sector'], unique=False)
    op.create_table('treasury_curve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('tenor_years', sa.Float(), nullable=False),
    sa.Column('par_yield', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curve_date', 'tenor_years', name='uq_ust_date_tenor')
    )
    op.create_index(op.f('ix_treasury_curve_curve_date'), 'treasury_curve', ['curve_date'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('yield_to_maturity', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cusip'], ['bonds.cusip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cusip', 'trade_date', name='uq_md_cusip_date')
    )
    op.create_index(op.f('ix_market_data_cusip'), 'market_data', ['cusip'], unique=False)
    op.create_index(op.f('ix_market_data_trade_date'), 'market_data', ['trade_date'], unique=False)
    op.create_table('residuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('actual_spread', sa.Float(), nullable=False),
    sa.Column('model_spread', sa.Float(), nullable=False),
    sa.Column('residual', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cusip'], ['bonds.cusip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cusip', 'trade_date', name='uq_resid_cusip_date')
    )
    op.create_index(op.f('ix_residuals_cusip'), 'residuals', ['cusip'], unique=False)
    op.create_index(op.f('ix_residuals_trade_date'), 'residuals', ['trade_date'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('residual', sa.Float(), nullable=False),
    sa.Column('expected_reversion_bps', sa.Float(), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cusip'], ['bonds.cusip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cusip', 'trade_date', name='uq_signal_cusip_date')
    )
    op.create_index(op.f('ix_signals_cusip'), 'signals', ['cusip'], unique=False)
    op.create_index(op.f('ix_signals_trade_date'), 'signals', ['trade_date'], unique=False)
    op.create_table('spreads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('g_spread', sa.Float(), nullable=False),
    sa.Column('i_spread', sa.Float(), nullable=False),
    sa.Column('z_spread', sa.Float(), nullable=False),
    sa.Column('oas', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cusip'], ['bonds.cusip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cusip', 'trade_date', name='uq_spread_cusip_date')
    )
    op.create_index(op.f('ix_spreads_cusip'), 'spreads', ['cusip'], unique=False)
    op.create_index(op.f('ix_spreads_trade_date'), 'spreads', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spreads_trade_date'), table_name='spreads')
    op.drop_index(op.f('ix_spreads_cusip'), table_name='spreads')
    op.drop_table('spreads')
    op.drop_index(op.f('ix_signals_trade_date'), table_name='signals')
    op.drop_index(op.f('ix_signals_cusip'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_residuals_trade_date'), table_name='residuals')
    op.drop_index(op.f('ix_residuals_cusip'), table_name='residuals')
    op.drop_table('residuals')
    op.drop_index(op.f('ix_market_data_trade_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_cusip'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_treasury_curve_curve_date'), table_name='treasury_curve')
    op.drop_table('treasury_curve')
    op.drop_index(op.f('ix_bonds_sector'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_rating'), table_name='bonds')
    op.drop_index(op.f('ix_bonds_issuer'), table_name='bonds')
    op.drop_table('bonds')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
